# Generated by Django 5.2.1 on 2025-05-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Бригадина Валерия Александровна', max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('email', models.EmailField(default='vabrigadina@edu.hse.ru', max_length=254)),
                ('phone', models.CharField(default='8 999 555 32 32', max_length=20)),
                ('resume', models.ImageField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classmate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='classmate_photos/')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationalProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Иностранные языки и межкультурная коммуникация', max_length=200)),
                ('link', models.URLField(default='https://www.hse.ru/ba/lang/')),
                ('what_i_study', models.TextField(default='Я углублённо изучаю два иностранных языка: английский и второй на выбор — в моём случае, это французский. Помимо языков, мы изучаем межкультурную коммуникацию, основы перевода, цифровые коммуникации, методику преподавания, а также русский как иностранный. Программа даёт возможность выбирать майноры и элективные курсы — это позволяет строить свою образовательную траекторию.')),
                ('what_i_learn', models.TextField(default='К окончанию обучения я смогу свободно говорить на двух иностранных языках, переводить тексты и устную речь, преподавать языки, вести проекты в сфере международного взаимодействия и использовать цифровые инструменты в своей работе. У нас много практики, стажировок и проектов, поэтому я не просто изучаю теорию, но и применяю знания на деле.')),
                ('benefits', models.TextField(default='Мне нравится, что здесь гибкая программа, есть англоязычный трек, возможность участвовать в международных обменах. Преподаватели — настоящие профессионалы, а атмосфера очень вдохновляющая. Мы участвуем в конференциях, встречах с работодателями, творческих и исследовательских проектах — это помогает расти как личностно, так и профессионально.')),
                ('prospects', models.TextField(default='После окончания программы я могу работать переводчиком, преподавателем, специалистом по международным коммуникациям, в сфере маркетинга, HR, в международных компаниях, культурных организациях. Можно пойти в магистратуру, заняться наукой или работать за границей.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_director_name', models.CharField(default='Боголепова Светлана Викторовна', max_length=200)),
                ('academic_director_photo', models.ImageField(blank=True, null=True, upload_to='management_photos/')),
                ('academic_director_email', models.EmailField(default='svbogolepova@hse.ru', max_length=254)),
                ('program_manager_name', models.CharField(default='Симонова Елена Алексеевна', max_length=200)),
                ('program_manager_photo', models.ImageField(blank=True, null=True, upload_to='management_photos/')),
                ('program_manager_email', models.EmailField(default='eakochetkova@hse.ru', max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
